# Generated by Django 3.1.7 on 2021-03-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, null=True, verbose_name='Apellidos')),
                ('codigo_estudiante', models.CharField(max_length=100, null=True, verbose_name='Codigo Estudiantil')),
                ('edad', models.CharField(max_length=10, null=True, verbose_name='Edad')),
                ('nombre_acudiente', models.CharField(max_length=100, null=True, verbose_name='Nombre del acudiente')),
                ('telefono_contacto', models.CharField(max_length=100, null=True, verbose_name='Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Contraseña')),
                ('grado', models.ForeignKey(blank=True, help_text='Seleccione un grado y asignelo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='student.grade', verbose_name='Asigne un grado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
