# Generated by Django 3.1.7 on 2021-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_convocatoria_docentes_entregaarchivos_entregaarchivosmodulo3_estudiantes_resultadosmodulo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100, null=True, verbose_name='Ingrese nombre de entidad financiera')),
                ('informacion', models.TextField(null=True, verbose_name='Informacion')),
                ('url', models.URLField(verbose_name='URL de entidad')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion de entidad financiera')),
                ('correo_electronico', models.CharField(max_length=100, null=True, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Entidades Financieras',
                'verbose_name_plural': 'Entidades Financieras',
            },
        ),
    ]
