# Generated by Django 3.1.7 on 2021-03-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='password',
        ),
    ]
