# Generated by Django 3.1.7 on 2021-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='codigo_estudiante',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Codigo Estudiantil'),
        ),
    ]
