# Generated by Django 3.1.7 on 2021-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210421_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaarchivos',
            name='nota',
            field=models.FloatField(max_length=10, null=True, verbose_name='Ingrese Nota'),
        ),
    ]
