# Generated by Django 3.1.7 on 2021-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210517_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaarchivosmodulo3',
            name='nota',
            field=models.FloatField(max_length=10, null=True, verbose_name='Ingrese Nota'),
        ),
    ]
