# Generated by Django 3.1.7 on 2021-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210517_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaarchivos',
            options={'verbose_name': 'Entrega Modulo 2', 'verbose_name_plural': 'Entregas Modulo 2'},
        ),
        migrations.AlterModelOptions(
            name='resultadosmodulo1',
            options={'verbose_name': 'Resultado Modulo 1', 'verbose_name_plural': 'Resultados Modulo 1'},
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='idea_negocio',
            field=models.TextField(max_length=255, null=True, verbose_name='Idea de negocio'),
        ),
        migrations.AlterField(
            model_name='entregaarchivos',
            name='nota',
            field=models.FloatField(max_length=10, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='entregaarchivos',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='entregaarchivos',
            name='rubrica',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Rubricas de calificacion'),
        ),
        migrations.AlterField(
            model_name='entregaarchivosmodulo3',
            name='nota',
            field=models.FloatField(max_length=10, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='entregaarchivosmodulo3',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='entregaarchivosmodulo3',
            name='rubrica',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Rubricas de calificacion'),
        ),
    ]
