# Generated by Django 3.1.7 on 2021-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_entregaarchivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaarchivos',
            name='formato_guia',
            field=models.FileField(blank=True, null=True, upload_to='static/archivos/', verbose_name='Plantilla Guia'),
        ),
    ]
