# Generated by Django 3.1.7 on 2021-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210529_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='idea_negocio',
            field=models.TextField(max_length=255, verbose_name='Idea de negocio'),
        ),
    ]
