# Generated by Django 3.1.7 on 2021-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210311_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, null=True, verbose_name='Apellidos')),
                ('documento', models.CharField(max_length=100, null=True, unique=True, verbose_name='Documento identidad')),
                ('edad', models.CharField(max_length=10, null=True, verbose_name='Edad')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo academico')),
                ('telefono_contacto', models.CharField(max_length=100, null=True, verbose_name='Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
