# Generated by Django 3.1.7 on 2021-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210529_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='area_desempeno',
            field=models.CharField(max_length=100, null=True, verbose_name='Area de desempeño'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='entidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='idea_negocio',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Idea de negocio'),
        ),
        migrations.AlterField(
            model_name='resultadosmodulo1',
            name='resultado_total',
            field=models.IntegerField(null=True, verbose_name='Resultado Total'),
        ),
    ]
