# Generated by Django 3.1.7 on 2021-03-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_docentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='grado',
            field=models.ForeignKey(blank=True, help_text='Seleccione un grado y asignelo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='student.docentes', verbose_name='Asigne un grado'),
        ),
    ]
