# Generated by Django 3.1.7 on 2021-03-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210313_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='docente',
            field=models.ForeignKey(blank=True, help_text='Seleccione un grado y asignelo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='student.docentes', verbose_name='Asigne un grado'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='grado',
            field=models.ForeignKey(blank=True, help_text='Seleccione un grado y asignelo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='student.grade', verbose_name='Asigne un grado'),
        ),
    ]
