# Generated by Django 3.1.7 on 2021-06-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210529_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocatoria',
            old_name='proxima_convocatoria',
            new_name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='activar_convocatoria',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='Cierre de plataforma'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='nombre_convocatoria',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre convocatoria'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='area_desempeno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area de desempeño'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad'),
        ),
    ]
