# Generated by Django 3.1.7 on 2021-03-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210313_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='docente',
            field=models.ForeignKey(blank=True, default=None, help_text='Seleccione un docente y asignelo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Docente', to='student.docentes', verbose_name='Asigne un docente'),
        ),
    ]
