# Generated by Django 3.1.7 on 2021-03-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210313_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='docente',
        ),
    ]
