# Generated by Django 3.1.7 on 2021-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_estudiantes_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaarchivos',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.estudiantes'),
        ),
    ]
