# Generated by Django 3.1.7 on 2021-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20210313_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaarchivos',
            name='nota',
            field=models.CharField(max_length=10, null=True, verbose_name='Ingrese Nota'),
        ),
        migrations.AddField(
            model_name='entregaarchivos',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Ingrese Observaciones'),
        ),
    ]
