# Generated by Django 3.1.7 on 2021-03-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20210313_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaarchivos',
            name='formato_guia',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Plantilla Guia'),
        ),
    ]
