# Generated by Django 3.1.7 on 2021-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20210324_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaarchivos',
            name='rubrica',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Rebrica de calificacion'),
        ),
    ]
