# Generated by Django 3.1.7 on 2021-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_entregaarchivos_rubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_convocatoria', models.BooleanField(default=False, verbose_name='Activar/Desactivar')),
                ('proxima_convocatoria', models.DateField(null=True, verbose_name='Apertura de plataforma')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
    ]
